services:
  db:
    container_name: betmaker_postgres
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:z

  backend:
    build: .
    container_name: betmaker_server
    restart: always
    volumes:
      - .:/code
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - db
